### ISSUE TITLE
Questions about results on ImageNet dataset

### ISSUE THREAD

**Issue by silent-chen** [mzhaoshuai/SplitNet-Divide-and-Co-training#4]
Hi, 

Good works!
I am reading the paper and finding that table 4 is kind of confusing. May I ask why the accuracies of M_i sometimes are greater than(or equals to)the full model (WRN-50-2, EfficientNet-B7)?

**Comment by mzhaoshuai** [comment]
> Hi,
> 
> Good works!
> I am reading the paper and finding that table 4 is kind of confusing. May I ask why the accuracies of M_i sometimes are greater than(or equals to)the full model (WRN-50-2, EfficientNet-B7)?

Acute observations. 
`M_i` of `EfficientNet-B7, S=2` is better or equal to the full model `EfficientNet-B7, S=1` . 
I think this is possibly due to the effect of co-training.
Honestly, I do not know the real reason and cannot show you more data now, but this is a reasonable one.
It is also consistent with the report of EfficietNet, i.e., `EfficientNet-B7 (84.4%, 66M, crop 600, wider, deeper) vs. EfficientNet-B6 (84.2%, 43M, crop 528),`.
EfficientNet-B6 may also achieve `84.4%` or `84.3%` with a bigger crop, 600. 

Some of the `M_i` is better than some full models, this is because some `M_i`s is bigger than what you think.
For example, `M_i` of `SE-ResNeXt-101, 64x4d` have similar capacity as `SE-ResNeXt-101, 32x4d`.
In this case, it is reasonable for `M_i` to get better performance than some relatively small full models.
This is decided by the dividing fashion.

Finally, this situation also demonstrates the superiority of increasing the number of networks and co-training.

**Comment by silent-chen** [comment]
Thanks for the rapid answering.

**Comment by mzhaoshuai** [comment]
> Thanks for the rapid answering.
> I think the co-training might be the reason. This is interesting if it works universally.
> When you refer to "bigger than what you think", do you mean the complexity of M_i is not similar to half of the full model complexity?

Somehow, yes.
If we only look at the `#Params`, one small network is roughly `1/S` as the original.
But, according to `Eq.(2)` and `Eq.(3)`, the `#Params` become `1/S`, but the number of output feature maps is `1/sqrt(S)` as the original.
In other words, `M_i`s produce more feature maps than `M` when they have the same `#Params` in total.
This is also the secret of group/depthwise convolution.

However, the above explanation is not so suitable for the division of `ResNeXt`.
As we divide the number of groups, and the number of feature map channels change with the groups linearly.

**Comment by silent-chen** [comment]
I understand. This is the same situation with EfficientNet. I would like to training co-training then.

May I ask whether the method performs well for small models like (EffcientNetB0-B3) on ImageNet?

**Comment by mzhaoshuai** [comment]
> I understand. This is the same situation with EfficientNet. I am interested in the effect of co-training and I will try to use co-training in my work then.
> 
> May I ask whether the method performs well for small models like (EffcientNetB0-B3) on ImageNet?

I think this method may not work well with small models like (EffcientNetB0-B3) on ImageNet.
It even does not work well with `Wide-ResNet-50` on ImageNet as I showed in the paper.
According to my practice, if your model is `3x` wide than `ResNet-50`, you will get a gain by dividing and co-training on ImageNet.
This also means it better to increase the number of networks in this situation rather than the width.

For small datasets, it seems dividing and co-training always works.

**Comment by silent-chen** [comment]
Thanks for your reply! I have a better understanding of the method now.

**Comment by silent-chen** [comment]
Hi,
One last question. Is the method works well when split>2 on ImageNet? Will more splits bring performance improvement like CIFAR-100?

**Comment by mzhaoshuai** [comment]
> Hi,
> One last question. Is the method works well when split>2 on ImageNet? Will more splits bring performance improvement like CIFAR-100?

I only test `S=2` on ImageNet.
This is decided by the sequential training method  I used (refer to the last paragraph of  `Sec. 4.4. Ablation study`) and limited resources.
E.g., the training of `EfficientNet-B7, S=2` takes 12+ days. You can use `tensorboard` to visualize the log and see the time.

I cannot tell you the answer as I never test it.
But I think it will work well with some super large networks like `FixResNeXt-101 32x48d` or `EfficientNet-L2`.
See https://paperswithcode.com/sota/image-classification-on-imagenet.

It will be easier to test the idea with a framework that supports concurrent training of multiple networks.

**Comment by silent-chen** [comment]
I will close the issue since all my questions have been answered.
Thanks for your patient reply.
